name: publish nuget package

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install libssl1.1 for netstandard2.0 compatibility
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1 || sudo apt-get install -y libssl1.0.0 || echo "libssl1.1 not available, please check compatibility"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}

    - name: Build sln to generate nupkg
      run: dotnet build

    - name: Publish NuGet package
      run: |
        for file in ${{ vars.PACKAGE_DIRECTORY }}/*.nupkg; do
          dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source ${{ vars.NUGET_SOURCE }};
        done
